# Generated by Django 5.1.6 on 2025-03-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimage',
            name='title',
            field=models.CharField(default='Default Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
