# Generated by Django 5.1.6 on 2025-03-12 18:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_carouselimage_title_alter_carouselimage_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselimage',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='carouselimage',
            name='title',
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
