# Generated by Django 5.1.6 on 2025-03-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_carouselimage_caption_alter_carouselimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimage',
            name='image',
            field=models.ImageField(upload_to='carousel_images/'),
        ),
    ]
