# Generated by Django 5.1.6 on 2025-03-14 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='home.product')),
            ],
        ),
    ]
