# Generated by Django 5.1.6 on 2025-03-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_contact_message_contact_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='pincode',
            field=models.CharField(default='000000', max_length=12),
        ),
    ]
