# Generated by Django 5.1.6 on 2025-03-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_contact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
