# Generated by Django 5.1.6 on 2025-03-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_quickenquiry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quickenquiry',
            options={},
        ),
        migrations.RenameField(
            model_name='quickenquiry',
            old_name='phone',
            new_name='mobile_number',
        ),
        migrations.RenameField(
            model_name='quickenquiry',
            old_name='message',
            new_name='query',
        ),
        migrations.AlterField(
            model_name='quickenquiry',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
