# Generated by Django 5.1.6 on 2025-03-16 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_quickenquiry_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuickEnquiry',
        ),
    ]
