# Generated by Django 5.1.6 on 2025-03-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_quickenquiry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quickenquiry',
            options={},
        ),
        migrations.RenameField(
            model_name='quickenquiry',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='quickenquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='quickenquiry',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='quickenquiry',
            name='query',
            field=models.TextField(),
        ),
    ]
