# Generated by Django 5.1.6 on 2025-03-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='whychooseus',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
