# Generated by Django 5.1.6 on 2025-03-16 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_galleryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.product'),
        ),
    ]
