# Generated by Django 5.1.6 on 2025-03-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_rename_subscribed_at_subscription_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='We use cookies to improve your experience.', max_length=255)),
                ('button_text', models.CharField(default='Accept', max_length=50)),
                ('privacy_policy_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
