# Generated by Django 5.1.6 on 2025-03-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='phone',
            field=models.CharField(default='N/A', max_length=15),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job',
            field=models.CharField(max_length=255),
        ),
    ]
