# Generated by Django 5.1.6 on 2025-03-31 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_category_catogary_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catogary_product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='catogary_Product',
        ),
    ]
