# Generated by Django 5.1.6 on 2025-04-04 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_businesshours'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryProduct',
        ),
        migrations.DeleteModel(
            name='CookieConsent',
        ),
    ]
