# Generated by Django 5.1.6 on 2025-04-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_delete_categoryproduct_delete_cookieconsent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdffile',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
