# Generated by Django 4.2 on 2025-06-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_alter_pdffile_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(upload_to='books/covers/')),
                ('pdf_file', models.FileField(upload_to='books/pdfs/')),
                ('category', models.CharField(choices=[('drive', 'Drive'), ('control_panel', 'Control & Panel'), ('door_drive', 'Door Drive'), ('overload', 'Overload')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
